<?php

namespace Tests\Unit\Repository;

use App\Models\Otp;
use App\Models\User;
use App\Repository\OtpRepository;
use Tests\Unit\UnitBaseTest;

/**
 * @author Chaprel John Villegas <vchapreljohn1@gmail.com>
 */
class OtpRepositoryTest extends UnitBaseTest
{
    /** @var OtpRepository */
    protected OtpRepository $otpRepository;

    /** @var User */
    protected User $user;

    /** @var Otp */
    protected Otp $otp;

    public function setUp(): void
    {
        parent::setUp();

        # Setup the repository and create a test user
        $this->otpRepository = new OtpRepository();
        $this->user = User::factory()->create();

        # Create a test OTP record (not expired, not used)
        $this->otp = Otp::create([
            'user_id' => $this->user->id,
            'code' => '123456',
            'expires_at' => now()->addMinutes(Otp::SHELF_LIFE), # not expired
            'verified_at' => null, # not used
        ]);
    }

    public function test_returns_valid_otp_when_exists_and_not_expired_or_used()
    {
        $validOtp = $this->otpRepository->getValidOtp($this->user, '123456');
        $this->assertNotNull($validOtp);
        $this->assertEquals($this->otp->code, $validOtp->code);
    }

    public function test_returns_null_when_otp_is_expired()
    {
        $this->otp->update(['expires_at' => now()->subMinutes()]); # Set OTP to expired
        $expiredOtp = $this->otpRepository->getValidOtp($this->user, '123456');
        $this->assertNull($expiredOtp);
    }

    public function test_returns_null_when_otp_is_used()
    {
        # Set OTP to used
        $this->otp->verified_at = now();
        $this->otp->save();

        $usedOtp = $this->otpRepository->getValidOtp($this->user, '123456');
        $this->assertNull($usedOtp);
    }

    public function test_returns_null_when_no_otp_found_for_given_code()
    {
        # Create a new OTP with a different code
        Otp::create([
            'user_id' => $this->user->id,
            'code' => '654321',
            'expires_at' => now()->addMinutes(Otp::SHELF_LIFE),
            'verified_at' => null,
        ]);

        # Attempt to retrieve an OTP with an invalid code
        $invalidOtp = $this->otpRepository->getValidOtp($this->user, '000000');
        $this->assertNull($invalidOtp);
    }

    public function test_returns_otp_in_an_hour_frequency_with_valid_code()
    {
        $otpCode = rand(100000, 999999);

        # Create OTP within last hour
        $validOtp = Otp::create([
            'user_id' => $this->user->id,
            'code' => $otpCode,
            'expires_at' => now()->addMinutes(Otp::SHELF_LIFE),
            'verified_at' => null,
        ]);

        # override the default created_at value generated by laravel
        $validOtp->created_at = now()->subMinutes(30);
        $validOtp->save();

        $otpInRange = $this->otpRepository->getOtpInAnHourFrequency($this->user, $otpCode);
        $this->assertNotNull($otpInRange);
        $this->assertEquals($validOtp->code, $otpInRange->code);
    }

    public function test_returns_null_for_otp_not_in_an_hour_frequency()
    {
        $otpCode = rand(100000, 999999);

        # Create OTP more than an hour ago
        $outOfRangeOtp = Otp::create([
            'user_id' => $this->user->id,
            'code' => $otpCode,
            'expires_at' => now()->addMinutes(Otp::SHELF_LIFE),
            'verified_at' => null,
        ]);

        # override the default created_at value generated by laravel
        $outOfRangeOtp->created_at = now()->subMinutes(90);
        $outOfRangeOtp->save();

        $otpOutOfRange = $this->otpRepository->getOtpInAnHourFrequency($this->user, $otpCode);
        $this->assertNull($otpOutOfRange);
    }

    public function test_returns_null_when_no_otp_found_for_given_code_in_an_hour_frequency()
    {
        # Create a valid OTP with a different code
        Otp::create([
            'user_id' => $this->user->id,
            'code' => '654321',
            'created_at' => now()->subMinutes(30),
            'updated_at' => now(),
            'expires_at' => now()->addMinutes(Otp::SHELF_LIFE),
            'verified_at' => null,
        ]);

        # Retrieve OTP with a different code
        $otpForDifferentCode = $this->otpRepository->getOtpInAnHourFrequency($this->user, '000000');
        $this->assertNull($otpForDifferentCode);
    }
}
